import type { EmergencyCategory, FacilityType, Specialty, SymptomCode, Urgency } from '@sanjeevani/types';
import type { Localized } from './localized';

export const SYMPTOM_LABELS: Record<SymptomCode, Localized> = {
  fever: { en: 'fever', hi: 'बुखार', hinglish: 'bukhar', bn: 'জ্বর' },
  chills: { en: 'chills', hi: 'कंपकंपी', hinglish: 'kapkapi', bn: 'কাঁপুনি' },
  body_ache: { en: 'body ache', hi: 'बदन दर्द', hinglish: 'badan dard', bn: 'গা ব্যথা' },
  fatigue: { en: 'tiredness', hi: 'थकान', hinglish: 'thakan', bn: 'ক্লান্তি' },
  headache: { en: 'headache', hi: 'सिर दर्द', hinglish: 'sir dard', bn: 'মাথা ব্যথা' },
  cough: { en: 'cough', hi: 'खांसी', hinglish: 'khansi', bn: 'কাশি' },
  sore_throat: { en: 'sore throat', hi: 'गले में दर्द', hinglish: 'gale mein dard', bn: 'গলা ব্যথা' },
  runny_nose: { en: 'cold or runny nose', hi: 'जुकाम', hinglish: 'zukam', bn: 'সর্দি বা নাক দিয়ে জল' },
  breathlessness: { en: 'breathlessness', hi: 'सांस फूलना', hinglish: 'saans phoolna', bn: 'শ্বাসকষ্ট' },
  wheezing: { en: 'wheezing', hi: 'सांस में सीटी', hinglish: 'saans mein seeti', bn: 'শ্বাসে শোঁ শোঁ শব্দ' },
  chest_pain: { en: 'chest pain', hi: 'सीने में दर्द', hinglish: 'seene mein dard', bn: 'বুকে ব্যথা' },
  palpitations: { en: 'racing heartbeat', hi: 'तेज़ धड़कन', hinglish: 'tez dhadkan', bn: 'বুক ধড়ফড়' },
  abdominal_pain: { en: 'stomach pain', hi: 'पेट दर्द', hinglish: 'pet dard', bn: 'পেটে ব্যথা' },
  nausea: { en: 'nausea', hi: 'जी मचलना', hinglish: 'ji machalna', bn: 'বমি বমি ভাব' },
  vomiting: { en: 'vomiting', hi: 'उल्टी', hinglish: 'ulti', bn: 'বমি' },
  diarrhea: { en: 'loose motions', hi: 'दस्त', hinglish: 'dast', bn: 'পাতলা পায়খানা' },
  constipation: { en: 'constipation', hi: 'कब्ज़', hinglish: 'kabz', bn: 'কোষ্ঠকাঠিন্য' },
  loss_of_appetite: { en: 'low appetite', hi: 'भूख न लगना', hinglish: 'bhookh na lagna', bn: 'খিদে কমে যাওয়া' },
  dizziness: { en: 'dizziness', hi: 'चक्कर', hinglish: 'chakkar', bn: 'মাথা ঘোরা' },
  fainting: { en: 'fainting', hi: 'बेहोशी', hinglish: 'behoshi', bn: 'অজ্ঞান হয়ে যাওয়া' },
  weakness: { en: 'weakness', hi: 'कमज़ोरी', hinglish: 'kamzori', bn: 'দুর্বলতা' },
  numbness: { en: 'numbness', hi: 'सुन्नपन', hinglish: 'sunnpan', bn: 'অসাড়তা' },
  confusion: { en: 'confusion', hi: 'भ्रम', hinglish: 'confusion', bn: 'অসংলগ্ন ভাব' },
  seizure: { en: 'seizure', hi: 'दौरा', hinglish: 'daura', bn: 'খিঁচুনি' },
  rash: { en: 'rash', hi: 'दाने', hinglish: 'daane', bn: 'ফুসকুড়ি' },
  itching: { en: 'itching', hi: 'खुजली', hinglish: 'khujli', bn: 'চুলকানি' },
  swelling: { en: 'swelling', hi: 'सूजन', hinglish: 'soojan', bn: 'ফোলা' },
  ear_pain: { en: 'ear pain', hi: 'कान दर्द', hinglish: 'kaan dard', bn: 'কানে ব্যথা' },
  eye_pain: { en: 'eye pain', hi: 'आंख में दर्द', hinglish: 'aankh mein dard', bn: 'চোখে ব্যথা' },
  eye_redness: { en: 'red eyes', hi: 'लाल आंखें', hinglish: 'laal aankhen', bn: 'চোখ লাল' },
  blurred_vision: { en: 'blurred vision', hi: 'धुंधला दिखना', hinglish: 'dhundhla dikhna', bn: 'ঝাপসা দেখা' },
  toothache: { en: 'toothache', hi: 'दांत दर्द', hinglish: 'daant dard', bn: 'দাঁতে ব্যথা' },
  back_pain: { en: 'back pain', hi: 'कमर दर्द', hinglish: 'kamar dard', bn: 'কোমরে ব্যথা' },
  joint_pain: { en: 'joint pain', hi: 'जोड़ों में दर्द', hinglish: 'jodon mein dard', bn: 'গাঁটে ব্যথা' },
  neck_stiffness: { en: 'stiff neck', hi: 'गर्दन में अकड़न', hinglish: 'gardan mein akdan', bn: 'ঘাড় শক্ত' },
  injury: { en: 'injury', hi: 'चोट', hinglish: 'chot', bn: 'আঘাত' },
  burn: { en: 'burn', hi: 'जलना', hinglish: 'jalna', bn: 'পোড়া' },
  bleeding: { en: 'bleeding', hi: 'खून आना', hinglish: 'khoon aana', bn: 'রক্তক্ষরণ' },
  painful_urination: { en: 'burning urine', hi: 'पेशाब में जलन', hinglish: 'peshab mein jalan', bn: 'প্রস্রাবে জ্বালা' },
  blood_in_urine: { en: 'blood in urine', hi: 'पेशाब में खून', hinglish: 'peshab mein khoon', bn: 'প্রস্রাবে রক্ত' },
  blood_in_stool: { en: 'blood in stool', hi: 'मल में खून', hinglish: 'mal mein khoon', bn: 'পায়খানায় রক্ত' },
  blood_in_vomit: { en: 'vomiting blood', hi: 'खून की उल्टी', hinglish: 'khoon ki ulti', bn: 'রক্ত বমি' },
  dehydration: { en: 'signs of dehydration', hi: 'पानी की कमी', hinglish: 'paani ki kami', bn: 'শরীরে জলের ঘাটতির লক্ষণ' },
  animal_bite: { en: 'animal bite', hi: 'जानवर का काटना', hinglish: 'jaanwar ka kaatna', bn: 'পশুর কামড়' },
  pregnancy_concern: { en: 'pregnancy concern', hi: 'गर्भावस्था से जुड़ी चिंता', hinglish: 'pregnancy se judi chinta', bn: 'গর্ভাবস্থা সংক্রান্ত উদ্বেগ' },
  anxiety: { en: 'anxiety', hi: 'बेचैनी', hinglish: 'bechaini', bn: 'উদ্বেগ' },
  low_mood: { en: 'low mood', hi: 'उदासी', hinglish: 'udaasi', bn: 'মন খারাপ' },
  insomnia: { en: 'trouble sleeping', hi: 'नींद न आना', hinglish: 'neend na aana', bn: 'ঘুমের সমস্যা' },
};

export const SPECIALTY_LABELS: Record<Specialty, Localized> = {
  emergency_medicine: { en: 'Emergency', hi: 'इमरजेंसी', hinglish: 'Emergency', bn: 'জরুরি বিভাগ' },
  general_medicine: { en: 'General Medicine', hi: 'जनरल मेडिसिन', hinglish: 'General Medicine', bn: 'জেনারেল মেডিসিন' },
  pediatrics: { en: 'Paediatrics', hi: 'शिशु रोग', hinglish: 'Bachchon ke doctor', bn: 'শিশু বিশেষজ্ঞ' },
  cardiology: { en: 'Cardiology', hi: 'हृदय रोग', hinglish: 'Cardiology', bn: 'হৃদরোগ' },
  neurology: { en: 'Neurology', hi: 'न्यूरोलॉजी', hinglish: 'Neurology', bn: 'স্নায়ুরোগ' },
  pulmonology: { en: 'Pulmonology', hi: 'फेफड़ा रोग', hinglish: 'Pulmonology', bn: 'ফুসফুস রোগ' },
  gastroenterology: { en: 'Gastroenterology', hi: 'पेट रोग', hinglish: 'Gastroenterology', bn: 'পেটের রোগ' },
  orthopedics: { en: 'Orthopaedics', hi: 'हड्डी रोग', hinglish: 'Haddi ke doctor', bn: 'হাড়ের ডাক্তার' },
  ent: { en: 'ENT', hi: 'नाक-कान-गला', hinglish: 'ENT', bn: 'নাক-কান-গলা' },
  ophthalmology: { en: 'Eye care', hi: 'नेत्र रोग', hinglish: 'Aankh ke doctor', bn: 'চোখের ডাক্তার' },
  dermatology: { en: 'Dermatology', hi: 'त्वचा रोग', hinglish: 'Skin ke doctor', bn: 'চর্মরোগ' },
  obstetrics_gynecology: { en: 'Obstetrics & Gynaecology', hi: 'स्त्री एवं प्रसूति रोग', hinglish: 'Gynaecology', bn: 'স্ত্রীরোগ ও প্রসূতি' },
  dental: { en: 'Dental', hi: 'दंत रोग', hinglish: 'Dentist', bn: 'দাঁতের ডাক্তার' },
  psychiatry: { en: 'Mental health', hi: 'मानसिक स्वास्थ्य', hinglish: 'Mental health', bn: 'মানসিক স্বাস্থ্য' },
  urology: { en: 'Urology', hi: 'मूत्र रोग', hinglish: 'Urology', bn: 'মূত্ররোগ' },
};

export const FACILITY_TYPE_LABELS: Record<FacilityType, Localized> = {
  emergency_department: { en: 'emergency department', hi: 'इमरजेंसी विभाग', hinglish: 'emergency department', bn: 'জরুরি বিভাগ' },
  hospital: { en: 'hospital', hi: 'अस्पताल', hinglish: 'hospital', bn: 'হাসপাতাল' },
  clinic: { en: 'clinic', hi: 'क्लिनिक', hinglish: 'clinic', bn: 'ক্লিনিক' },
  pharmacy: { en: 'pharmacy', hi: 'दवा की दुकान', hinglish: 'medical store', bn: 'ওষুধের দোকান' },
  diagnostic_lab: { en: 'diagnostic lab', hi: 'जांच केंद्र', hinglish: 'lab', bn: 'পরীক্ষাগার' },
};

export const URGENCY_LABELS: Record<Urgency, Localized> = {
  self_care: { en: 'Home care', hi: 'घर पर देखभाल', hinglish: 'Ghar par dekhbhal', bn: 'বাড়িতে যত্ন' },
  routine: { en: 'See a doctor soon', hi: 'जल्द डॉक्टर को दिखाएं', hinglish: 'Jaldi doctor ko dikhayein', bn: 'শিগগিরই ডাক্তার দেখান' },
  urgent: { en: 'See a doctor today', hi: 'आज ही डॉक्टर को दिखाएं', hinglish: 'Aaj hi doctor ko dikhayein', bn: 'আজই ডাক্তার দেখান' },
  emergency: { en: 'Emergency', hi: 'इमरजेंसी', hinglish: 'Emergency', bn: 'জরুরি বিভাগ' },
};

export const EMERGENCY_CATEGORY_LABELS: Record<EmergencyCategory, Localized> = {
  cardiac: { en: 'Possible heart emergency', hi: 'दिल से जुड़ी संभावित इमरजेंसी', hinglish: 'Dil se judi emergency ho sakti hai', bn: 'হৃদরোগের জরুরি অবস্থা হতে পারে' },
  breathing: { en: 'Serious breathing difficulty', hi: 'सांस लेने में गंभीर दिक्कत', hinglish: 'Saans lene mein gambhir dikkat', bn: 'শ্বাস নিতে মারাত্মক কষ্ট' },
  stroke: { en: 'Possible stroke signs', hi: 'स्ट्रोक (लकवा) के संभावित लक्षण', hinglish: 'Stroke (lakwa) ke lakshan ho sakte hain', bn: 'স্ট্রোকের লক্ষণ হতে পারে' },
  unconscious: { en: 'Person not responding', hi: 'व्यक्ति होश में नहीं है', hinglish: 'Vyakti hosh mein nahi hai', bn: 'তিনি সাড়া দিচ্ছেন না' },
  major_trauma: { en: 'Serious injury', hi: 'गंभीर चोट', hinglish: 'Gambhir chot', bn: 'গুরুতর আঘাত' },
  severe_bleeding: { en: 'Heavy bleeding', hi: 'बहुत ज़्यादा खून बहना', hinglish: 'Bahut zyada khoon behna', bn: 'প্রচুর রক্তক্ষরণ' },
  seizure: { en: 'Seizure', hi: 'दौरा', hinglish: 'Daura (seizure)', bn: 'খিঁচুনি' },
  anaphylaxis: { en: 'Severe allergic reaction', hi: 'गंभीर एलर्जी', hinglish: 'Gambhir allergy', bn: 'মারাত্মক অ্যালার্জি' },
  poisoning: { en: 'Possible poisoning', hi: 'संभावित ज़हर', hinglish: 'Zeher ka khatra', bn: 'বিষক্রিয়া হতে পারে' },
  self_harm: { en: 'You deserve support right now', hi: 'आपको अभी सहारा मिलना चाहिए', hinglish: 'Aapko abhi sahara milna chahiye', bn: 'এই মুহূর্তে আপনার পাশে কারও থাকা দরকার' },
  severe_burn: { en: 'Serious burn', hi: 'गंभीर जलन', hinglish: 'Gambhir jalan', bn: 'গুরুতর পোড়া' },
  obstetric: { en: 'Pregnancy emergency', hi: 'गर्भावस्था इमरजेंसी', hinglish: 'Pregnancy emergency', bn: 'গর্ভাবস্থার জরুরি অবস্থা' },
  infant_danger: { en: 'Baby needs urgent care', hi: 'शिशु को तुरंत इलाज चाहिए', hinglish: 'Baby ko turant ilaaj chahiye', bn: 'বাচ্চার এখনই চিকিৎসা দরকার' },
  meningitis_signs: { en: 'Fever with danger signs', hi: 'खतरे के लक्षणों के साथ बुखार', hinglish: 'Khatre ke lakshanon ke saath bukhar', bn: 'বিপদচিহ্ন সহ জ্বর' },
  user_requested: { en: 'Emergency help', hi: 'इमरजेंसी मदद', hinglish: 'Emergency madad', bn: 'জরুরি সাহায্য' },
};
